import { CheckCircle, Clock, SearchX } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const asArray = (value) => (Array.isArray(value) ? value.filter(Boolean) : []);

export default function ReportCard({ reportData, isReportLoading }) {
  if (isReportLoading) {
    return (
      <div className="flex min-h-[300px] flex-col items-center justify-center gap-6 rounded-3xl border border-slate-700/50 bg-slate-800/80 p-6 shadow-xl backdrop-blur-md">
        <div className="flex animate-pulse flex-col items-center gap-4">
          <Clock size={32} className="animate-spin text-slate-500" />
          <p className="font-medium text-slate-400">Loading the latest stored report...</p>
        </div>
      </div>
    );
  }

  if (!reportData) {
    return (
      <div className="flex min-h-[200px] flex-col items-center justify-center gap-6 rounded-3xl border border-slate-700/50 bg-slate-800/80 p-6 text-center shadow-xl backdrop-blur-md">
        <div className="mb-2 flex h-16 w-16 items-center justify-center rounded-full bg-slate-700/50">
          <SearchX size={28} className="text-slate-400" />
        </div>
        <p className="font-medium text-slate-300">No stored AI report is available for this asset yet.</p>
        <p className="text-sm text-slate-500">Reports are generated by the backend scheduler, not by page views.</p>
      </div>
    );
  }

  const { final_content, metadata = {}, unavailable } = reportData;
  const readiness = metadata.readiness || {};
  const qualityStatus = metadata.quality_status || (metadata.is_pass ? 'pass' : '');
  const isScheduledPending = unavailable && metadata.reason === 'scheduled_report_not_ready';
  const isBlocked = unavailable || readiness.status === 'blocked' || qualityStatus === 'blocked';

  if (isScheduledPending) {
    return (
      <div className="flex min-h-[220px] flex-col justify-center gap-4 rounded-3xl border border-slate-700/50 bg-slate-800/80 p-6 text-center shadow-xl backdrop-blur-md">
        <div className="mx-auto mb-2 flex h-16 w-16 items-center justify-center rounded-full bg-slate-700/50">
          <Clock size={28} className="text-slate-400" />
        </div>
        <p className="font-medium text-slate-300">The scheduled AI report is not ready yet.</p>
        <p className="text-sm text-slate-500">
          The page only displays stored scheduled reports. It does not trigger a fresh LLM generation.
        </p>
      </div>
    );
  }

  if (isBlocked) {
    return (
      <div className="flex min-h-[220px] flex-col justify-center gap-4 rounded-3xl border border-amber-500/30 bg-slate-800/80 p-6 shadow-xl backdrop-blur-md">
        <div className="flex items-center gap-2 font-bold text-amber-300">
          <SearchX size={22} />
          Report unavailable
        </div>
        <p className="text-sm leading-6 text-slate-300">
          Required source data is missing, so the scheduled report was not written.
        </p>
        {asArray(readiness.blocking_reasons).length > 0 && (
          <ul className="list-disc space-y-1 pl-5 text-sm text-slate-400">
            {asArray(readiness.blocking_reasons).map((reason) => (
              <li key={reason}>{reason}</li>
            ))}
          </ul>
        )}
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6 rounded-3xl border border-slate-700/50 bg-slate-800/80 p-6 shadow-xl backdrop-blur-md">
      <div className="flex items-center justify-between">
        <h3 className="text-xl font-bold">
          AI Research Report
        </h3>
        <span className="flex items-center gap-1.5 rounded-full border border-emerald-500/30 bg-emerald-500/20 px-4 py-1.5 text-sm font-bold text-emerald-400 shadow-sm">
          <CheckCircle size={16} /> Complete
        </span>
      </div>

      <div className="rounded-2xl border border-slate-700/50 bg-slate-900/50 p-6 shadow-inner">
        <div
          className="prose prose-invert prose-slate max-w-none
          prose-headings:font-bold prose-headings:text-slate-100
          prose-a:text-emerald-400 prose-strong:text-slate-200 prose-ul:pl-4"
        >
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {final_content || 'The stored report body is empty.'}
          </ReactMarkdown>
        </div>
      </div>
    </div>
  );
}
