export const ASSET_NAMES = {
  "^GSPC": "S&P 500",
  "^NDX": "Nasdaq 100",
  "^KS11": "KOSPI",
  "^KQ11": "KOSDAQ",
  "KRW=X": "USD/KRW",
  USDKRW: "USD/KRW",

  "BTC-USD": "Bitcoin",
  "ETH-USD": "Ethereum",
  "SOL-USD": "Solana",
  Bitcoin: "Bitcoin",
  Ethereum: "Ethereum",

  "GC=F": "Gold",
  "SI=F": "Silver",
  "CL=F": "WTI Crude Oil",
  XAU: "Gold",
  XAG: "Silver",
  Gold: "Gold",
  Silver: "Silver",

  "^IRX": "US 3M Treasury Yield",
  "^FVX": "US 5Y Treasury Yield",
  "^TNX": "US 10Y Treasury Yield",
  "^TYX": "US 30Y Treasury Yield",
  DGS2MO: "US 2M Treasury Yield",
  DGS3MO: "US 3M Treasury Yield",
  DGS10: "US 10Y Treasury Yield",
  "US 3M Treasury": "US 3M Treasury Yield",
  "US 10Y Treasury": "US 10Y Treasury Yield",

  "0101500": "Korea 1Y Treasury Yield",
  "0102000": "Korea 10Y Treasury Yield",
  KR_BOND_1Y: "Korea 1Y Treasury Yield",
  KR_BOND_3Y: "Korea 3Y Treasury Yield",
  KR_BOND_10Y: "Korea 10Y Treasury Yield",
  KTB_1Y: "Korea 1Y Treasury Yield",
  KTB_3Y: "Korea 3Y Treasury Yield",
  KTB_5Y: "Korea 5Y Treasury Yield",
  KTB_10Y: "Korea 10Y Treasury Yield",
  KTB_20Y: "Korea 20Y Treasury Yield",
  KTB_30Y: "Korea 30Y Treasury Yield",
  "KR 1Y Treasury": "Korea 1Y Treasury Yield",
  "KR 10Y Treasury": "Korea 10Y Treasury Yield",
  "KR 30Y Treasury": "Korea 30Y Treasury Yield",

  AAPL: "Apple",
  MSFT: "Microsoft",
  NVDA: "NVIDIA",
  GOOGL: "Alphabet",
  AMZN: "Amazon",
  META: "Meta",
  "BRK-B": "Berkshire Hathaway",
  LLY: "Eli Lilly",
  AVGO: "Broadcom",
  TSLA: "Tesla",

  "005930": "Samsung Electronics",
  "000660": "SK Hynix",
  "373220": "LG Energy Solution",
  "207940": "Samsung Biologics",
  "005380": "Hyundai Motor",
  "000270": "Kia",
  "068270": "Celltrion",
  "005490": "POSCO Holdings",
  "035420": "NAVER",
  "105560": "KB Financial Group",
  "005930.KS": "Samsung Electronics",
  "000660.KS": "SK Hynix",
  "373220.KS": "LG Energy Solution",
  "207940.KS": "Samsung Biologics",
  "005380.KS": "Hyundai Motor",
  "000270.KS": "Kia",
  "068270.KS": "Celltrion",
  "005490.KS": "POSCO Holdings",
  "035420.KS": "NAVER",
  "105560.KS": "KB Financial Group",
  "Samsung Electronics": "Samsung Electronics",
  "SK Hynix": "SK Hynix",
  "LG Energy Solution": "LG Energy Solution",
  "Samsung Biologics": "Samsung Biologics",
  "Hyundai Motor": "Hyundai Motor",
  Kia: "Kia",
  Celltrion: "Celltrion",
  "POSCO Holdings": "POSCO Holdings",
  NAVER: "NAVER",
  "KB Financial Group": "KB Financial Group",
};

export const resolveAssetName = (...keys) => {
  for (const key of keys) {
    if (!key) continue;
    if (ASSET_NAMES[key]) return ASSET_NAMES[key];
    const stripped = String(key).replace(".KS", "").replace(".KQ", "");
    if (ASSET_NAMES[stripped]) return ASSET_NAMES[stripped];
  }
  const fallback = keys.find(Boolean);
  return fallback ? String(fallback).replace(".KS", "").replace(".KQ", "") : "";
};
